spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888/
      name: user-service
  profiles:
    active: dev

logging:
  level:
    org.springframework.boot.context.config: debug