
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.naver.com  # 또는 smtp.gmail.com
    port: 587
    username: alog_gachon@naver.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${LOCAL_DB_URL}
    #    url: jdbc:postgresql://localhost:5432/devdb
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 필요에 따라 create, none 등 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  # 필요 시 로깅
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
  config:
    import: optional:.env[.properties]

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 60      # 1시간
  refresh-expiration: 3000   # 50시간
  reset-password-expiration: 15 # 15분

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: https://a-log.site/oauth/google/redirect
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: https://a-log.site/oauth/kakao/redirect
springdoc:
  swagger-ui:
    path: /swagger-ui.html


#AWS S3
cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_S3_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    stack:
      auto: false


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  prometheus:
    metrics:
      export:
        enabled: true