spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: alog_gachon@naver.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: redis  # service 이름으로 접근
      port: 6379

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace

  config:
    activate:
      on-profile: onpremise

#  kafka:
#    bootstrap-servers: kafka:9092  # 추후 kafka 서비스 이름으로 수정
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 60
  refresh-expiration: 3000
  reset-password-expiration: 15

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://user-service.example.com/oauth/google/redirect
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://user-service.example.com/oauth/kakao/redirect

springdoc:
  swagger-ui:
    path: /swagger-ui.html

#AWS S3
cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_S3_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    stack:
      auto: false