spring:
  mail:
    host: smtp.naver.com  # 또는 smtp.gmail.com
    port: 587
    username: alog_gachon@naver.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service
    username: gucci
    password: ${POSTGRESQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 필요에 따라 create, none 등 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  # 필요 시 로깅
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
  config:
    import: optional:.env[.properties]

  server:
    port: 8081
jwt:
  secret: ${JWT_SECRET}
  expiration: 3000 #분단위