spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testdb
    username: testuser
    password: ${TEST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format_sql: true