name: Close Jira Issue

on:
  issues:
    types: [closed]

jobs:
  transition-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Jira 로그인
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}


      - name: Jira 상태 변경 (Done)
        run: |
          TITLE="${{ github.event.issue.title }}"
          ISSUE_KEY=$(echo "$TITLE" | grep -oE '[A-Z]+-[0-9]+')
          echo "Jira Issue Key: $ISSUE_KEY"

          echo "ISSUE_KEY=$ISSUE_KEY" >> $GITHUB_ENV

      - name: Transition to Done
        if: env.ISSUE_KEY != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.ISSUE_KEY }}
          transition: 완료